<?php
# This file was automatically generated by the MediaWiki 1.42.7
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "MentiSphere";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://localhost:8080";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo-icon.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "mariadb";
$wgDBname = "mentisphere_wiki";
$wgDBuser = "root";
$wgDBpassword = "mentisphere_dev_2024";

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "3eb9b1734a55693b7098be64c021c1d274673bf12fdc9a5e795d038eb400af9a";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "09a6bbf7f1842f81";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector-2022";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# End of automatically generated settings.
# Add more configuration options below.

# Citizen Skin
wfLoadSkin( 'citizen' );
$wgDefaultSkin = 'citizen';

# Custom Namespaces
define( 'NS_AGENT', 3000 );
define( 'NS_AGENT_TALK', 3001 );
define( 'NS_KNOWLEDGE', 3010 );
define( 'NS_KNOWLEDGE_TALK', 3011 );
define( 'NS_SKILL', 3020 );
define( 'NS_SKILL_TALK', 3021 );
define( 'NS_ORCHESTRATOR', 3030 );
define( 'NS_ORCHESTRATOR_TALK', 3031 );

$wgExtraNamespaces[NS_AGENT] = 'Agent';
$wgExtraNamespaces[NS_AGENT_TALK] = 'Agent_talk';
$wgExtraNamespaces[NS_KNOWLEDGE] = 'Knowledge';
$wgExtraNamespaces[NS_KNOWLEDGE_TALK] = 'Knowledge_talk';
$wgExtraNamespaces[NS_SKILL] = 'Skill';
$wgExtraNamespaces[NS_SKILL_TALK] = 'Skill_talk';
$wgExtraNamespaces[NS_ORCHESTRATOR] = 'Orchestrator';
$wgExtraNamespaces[NS_ORCHESTRATOR_TALK] = 'Orchestrator_talk';

# Enable subpages in custom namespaces
$wgNamespacesWithSubpages[NS_AGENT] = true;
$wgNamespacesWithSubpages[NS_KNOWLEDGE] = true;
$wgNamespacesWithSubpages[NS_SKILL] = true;
$wgNamespacesWithSubpages[NS_ORCHESTRATOR] = true;

# Enable content namespaces for search
$wgContentNamespaces[] = NS_AGENT;
$wgContentNamespaces[] = NS_KNOWLEDGE;
$wgContentNamespaces[] = NS_SKILL;
